name: Linter and Codestyle checks 💅

on:
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Check codestyle
        run: npm run prettier
