name: Publish release 🚀
on:
  release:
    types: [published]
permissions: write-all
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: Install dependencies
        run: npm install
      - name: Bump version
        run: npm version --no-git-tag-version "${{ github.ref_name }}"
      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        with:
          message: 'New release ${{ github.ref_name }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
