name: Type Checking 🤌

on:
  pull_request:
    branches:
      - '**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: npm install
      - name: Type Checking
        run: npm run lint:tsc
